### ISSUE TITLE
pysimlのimportでエラーが発生

### ISSUE THREAD

**Issue by mochimochikun** [ricosjp/siml#1]
IsoGCNやPENNの論文を拝見し、手元で動かしたくなったのでpysimlをインストールしたのですが、importで以下のようなエラーが発生しました。
![Screenshot from 2023-11-29 15-02-02](https://github.com/ricosjp/siml/assets/87526616/b348a126-8870-4fbd-afa4-f7f106240886)
手元の環境は[Dockerhubから引っ張ってきたイメージ](https://hub.docker.com/r/ludotech/python3.9-poetry)を使用して仮想環境を構築しており、インストールは`python3.9 -m pip install pysiml`のコマンドで実施しました。(pipのupgradeも済ませています。)

少し調査をしてみたところnumbaのバージョンが問題なのではないかとの情報を見つけたので、numbaをアンインストールしてから、0.58.1のものを再インストールしてみるとエラーなくimportすることができました。

もしpysimlの方のバグであればpipの依存関係など修正していただけるとありがたいです。そうではなく、こちらの手順や環境に問題があるようであればお手数ですが教えていただきたいです。

**Comment by yellowshippo** [comment]
ご報告いただきありがとうございます。暫定的にですが、下記のようにしていただくと正しく import できるかと思います:
```
$ python3.9 -m pip install femio==0.3.3.dev202311300634 siml
```

厳密にはこれは siml の問題ではなく しml

**Comment by yellowshippo** [comment]
ご報告いただきありがとうございます。暫定的にですが、下記のようにしていただくと正しく import できるかと思います:

$ python3.9 -m pip install femio==0.3.3.dev202311300634 siml
厳密にはこれは siml の問題ではなく siml

**Comment by yellowshippo** [comment]
ご報告いただきありがとうございます。暫定的にですが、下記のようにしていただくと正しく import できるかと思います:
```
$ python3.9 -m pip install femio==0.3.3.dev202311300634 siml
```
厳密にはこれは siml の問題ではなく siml が依存している [femio](https://github.com/ricosjp/femio) の問題でして、次バージョン (0.3.3) で修正される予定ですが、femio 0.3.3 の本リリースがまだのため、プレリリース版をお使いいただく形となります。

以上、よろしくお願いいたします。
